name: yaml-example
runtime: yaml
description: Create a Deployment with auto-naming
resources:
  deployment:
    type: kubernetes:apps/v1:Deployment
    properties:
      metadata:
        labels:
          app: nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx
                image: nginx:1.14.2
                ports:
                  - containerPort: 80
---
name: yaml-example
runtime: yaml
description: Create a Deployment with a user-specified name
resources:
  deployment:
    type: kubernetes:apps/v1:Deployment
    properties:
      metadata:
        name: nginx-deployment
        labels:
          app: nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx
                image: nginx:1.14.2
                ports:
                  - containerPort: 80
